
INSERT INTO `ElectronicAddress` (`Identifier`) VALUES
('111-222-3333'),
('4056057080'),
('732-123-4567'),
('amaclead@gmail.com'),
('art@venere.org'),
('augusttubman@gmail.com'),
('augustubman@yahoo.com'),
('calbares@gmail.com'),
('donette.foller@cox.net'),
('gladys.rim@rim.org'),
('gruta@cox.net'),
('jbutt@gmail.com'),
('josephine_darakjy@darakjy.org'),
('kiley.caldarera@aol.com'),
('kris@gmail.com'),
('leota@hotmail.com'),
('lexter@dexter.com'),
('lpaprocki@hotmail.com'),
('mattie@aol.com'),
('meaghan@hotmail.com'),
('minna_amigon@yahoo.com'),
('mitsue_tollner@yahoo.com'),
('sage_wieser@cox.net'),
('simona@morasca.com'),
('yuki_whobrey@aol.com');
